server:
  port: 9090

logging:
  level:
    com.memoritta: debug
    root: info

spring:
  security:
    user:
      name: admin
      password: admin
  redis:
    host: localhost
    port: 6379
    password: qazxsw123
    database: 0
  data:
    mongodb:
      uri: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/yapp-db?authSource=admin"
      auto-index-creation: true


serverConfig:
  version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, env
  endpoint:
    health:
      show-details: always