server:
  port: 9090
  log: "/home/yapp/server/yapp.log"

logging:
  level:
    com.memoritta: debug
    root: info

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.pem
    user:
      name: admin
      password: admin
  data:
    redis:
      host: localhost
      port: 6379
      password: qazxsw123
      database: 0
    mongodb:
      uri: "mongodb://user:qazxsw123@localhost:27017/yapp-db?authSource=admin"
      auto-index-creation: true


serverConfig:
  version: "1.0.0"

question:
  ref:
    description-max-length: 200

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, env
  endpoint:
    health:
      show-details: always
openai:
  url: "https://api.openai.com/v1"
  api-key: "${OPENAI_API_KEY:changeme}"
  organization: "org-n9AnfI7a4lvpGr50hbypFLxB"
  project: "proj_5ODKT8ABkqMtUdXihb10kbIX"
