server:
  port: 9090

logging:
  level:
    com.memoritta: debug
    root: info

spring:
  redis:
    host: localhost
    port: 6379
    password: qazxsw123
    database: 0

serverConfig:
  version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, env
  endpoint:
    health:
      show-details: always