name: Deploy to PROD

on:
  create:
    branches:
      - 'release/**'

jobs:
  deploy:
    if: ${{ github.ref_type == 'branch' }}
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Restart backend and frontend
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SERVER_HOME: ${{ vars.SERVER_HOME }}
          FRONTEND_HOME: ${{ vars.FRONTEND_HOME }}
          SERVER_SCRIPT: ${{ vars.SERVER_SCRIPT }}
          FRONTEND_SCRIPT: ${{ vars.FRONTEND_SCRIPT }}
        run: |
          set -e
          for attempt in 1 2 3; do
            output=$(ATTEMPT="$attempt" ./scripts/restart-services.sh 2>&1)
            status=$?
            echo "$output"
            if [ $status -ne 0 ]; then
              exit $status
            fi
            if ! echo "$output" | grep -q "Another restart is in progress. Exiting."; then
              exit 0
            fi
            if [ $attempt -eq 3 ]; then
              echo "give up"
              exit 0
            fi
            sleep_time=$((30 + RANDOM % 21 + 10))
            echo "Another restart in progress during attempt #$attempt. Wait ${sleep_time}s before retry #$((attempt+1))"
            sleep "$sleep_time"
          done
