name: Deploy to PROD on merge

on:
  pull_request:
    branches: [ main ]
    types:
      - closed

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true }}
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
