name: Deploy to PROD

on:
  create:
    branches:
      - 'release/**'

jobs:
  deploy:
    if: ${{ github.ref_type == 'branch' }}
    environment: PROD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
