name: Deploy to PROD

on:
  workflow_run:
    workflows: ["Integration Tests"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy placeholder
        run: echo "Deployment step removed"

