name: Restart services after merge

on:
  push:
    branches: [ main ]

jobs:
  restart:
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v4
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Restart backend and frontend
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SERVER_HOME: ${{ vars.SERVER_HOME }}
          FRONTEND_HOME: ${{ vars.FRONTEND_HOME }}
          SERVER_SCRIPT: ${{ vars.SERVER_SCRIPT }}
          FRONTEND_SCRIPT: ${{ vars.FRONTEND_SCRIPT }}
        run: ./scripts/restart-services.sh
